version: '3'
services:
# MySQL services, use this only for development and/or testing
  school_service_mysql_dev:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school_service_mysql_dev
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default
  school_service_mysql_test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: school_service_mysql_test
    networks:
      - default
